import { Platform, StyleSheet } from "react-native";
import { COLORS } from "./theme";

export const AUTH_WEB_INPUT_RESET =
  Platform.OS === "web"
    ? ({
        outlineStyle: "none",
        outlineWidth: 0,
        outlineColor: "transparent",
        boxShadow: "none",
      } as any)
    : null;

export const authStyles = StyleSheet.create({
  flex: {
    flex: 1,
  },
  screen: {
    flex: 1,
    backgroundColor: "#F6FAFF",
    position: "relative",
    overflow: "hidden",
  },
  glow: {
    position: "absolute",
    borderRadius: 9999,
    opacity: 0.5,
  },
  glowTop: {
    width: 300,
    height: 300,
    backgroundColor: "rgba(142, 202, 230, 0.35)",
    top: -80,
    left: -90,
  },
  glowBottom: {
    width: 360,
    height: 360,
    backgroundColor: "rgba(255, 183, 3, 0.16)",
    right: -120,
    bottom: -120,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  brandWrap: {
    marginBottom: 28,
    alignItems: "center",
  },
  brand: {
    color: "#0A6F88",
    fontWeight: "800",
    letterSpacing: -0.8,
  },
  card: {
    width: "100%",
    maxWidth: 620,
    backgroundColor: "rgba(255,255,255,0.92)",
    borderWidth: 1,
    borderColor: "rgba(189, 200, 205, 0.36)",
    shadowColor: "#0F3554",
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.1,
    shadowRadius: 36,
    elevation: 10,
  },
  headerBlock: {
    alignItems: "center",
    marginBottom: 28,
  },
  title: {
    color: "#102A43",
    fontWeight: "800",
    marginBottom: 10,
  },
  subtitle: {
    color: "#4F6470",
    fontSize: 16,
    lineHeight: 24,
    textAlign: "center",
  },
  formBlock: {
    gap: 16,
  },
  fieldBlock: {
    gap: 8,
  },
  row: {
    flexDirection: "row",
    gap: 12,
  },
  rowItem: {
    flex: 1,
    minWidth: 0,
  },
  label: {
    color: "#102A43",
    fontSize: 15,
    fontWeight: "700",
  },
  inputShell: {
    minHeight: 58,
    borderWidth: 1,
    borderColor: "#D6E1EA",
    backgroundColor: "#F3F7FB",
    borderRadius: 14,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
  },
  inputShellFocused: {
    borderColor: "#D6E1EA",
    shadowOpacity: 0,
    elevation: 0,
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    color: "#102A43",
    fontSize: 16,
    paddingVertical: Platform.OS === "web" ? 14 : 12,
    borderWidth: 0,
  },
  multilineInput: {
    minHeight: 110,
    textAlignVertical: "top",
  },
  visibilityButton: {
    marginLeft: 10,
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  helperText: {
    color: "#6E7F8D",
    fontSize: 13,
    lineHeight: 18,
  },
  successText: {
    color: "#2E7D32",
    fontSize: 14,
    fontWeight: "600",
  },
  warningText: {
    color: COLORS.accentOrange,
    fontSize: 14,
    fontWeight: "600",
  },
  errorText: {
    color: "#C62828",
    fontSize: 14,
    fontWeight: "600",
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  checkboxButton: {
    width: 24,
    height: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#C3D3DD",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  checkboxButtonActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
  },
  checkboxLabelWrap: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  checkboxLabel: {
    color: "#4F6470",
    fontSize: 14,
    lineHeight: 22,
  },
  checkboxLink: {
    color: "#0A6F88",
    fontWeight: "700",
  },
  textButton: {
    alignSelf: "flex-end",
    marginTop: -2,
  },
  textButtonLabel: {
    color: "#0A6F88",
    fontSize: 15,
    fontWeight: "600",
  },
  primaryButton: {
    marginTop: 4,
    minHeight: 56,
    borderRadius: 14,
    backgroundColor: COLORS.primary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    shadowColor: "#219ebc",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 4,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "800",
  },
  secondaryButton: {
    minHeight: 56,
    borderRadius: 14,
    backgroundColor: COLORS.secondary,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  secondaryButtonText: {
    color: "#6C4B00",
    fontSize: 17,
    fontWeight: "800",
  },
  ghostButton: {
    minHeight: 54,
    borderRadius: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D6E1EA",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  ghostButtonText: {
    color: "#123042",
    fontSize: 16,
    fontWeight: "700",
  },
  buttonDisabled: {
    opacity: 0.58,
  },
  dividerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginVertical: 2,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: "rgba(110, 121, 125, 0.22)",
  },
  dividerText: {
    color: "#6E797D",
    fontSize: 15,
    fontWeight: "600",
  },
  infoBox: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D6E1EA",
    backgroundColor: "#F3F7FB",
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  infoBoxText: {
    color: "#102A43",
    fontSize: 15,
    lineHeight: 22,
    textAlign: "center",
  },
  footer: {
    marginTop: 24,
    color: "#6E7F8D",
    fontSize: 14,
    lineHeight: 22,
    textAlign: "center",
    maxWidth: 360,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(13, 25, 34, 0.45)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    maxHeight: "72%",
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderWidth: 1,
    borderColor: "#E2ECF1",
  },
  modalTitle: {
    color: "#102A43",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 12,
  },
});
