import { StyleSheet } from "react-native";

export const clientesStyles = StyleSheet.create({
  toolbarCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 12,
    borderWidth: 1,
    borderColor: "#D8E4EE",
    marginBottom: 14,
    shadowColor: "#0A2A43",
    shadowOpacity: 0.06,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 3,
  },
  scrollSection: {
    width: "100%",
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  },
  searchRowCompact: {
    flexWrap: "wrap",
  },
  searchInputWrap: {
    flex: 1,
    minWidth: 220,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: "#D2E2EE",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 4,
    backgroundColor: "#F9FCFF",
  },
  searchInput: {
    flex: 1,
    minHeight: 48,
    color: "#023047",
    fontSize: 16,
  },
  filterButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#D2E2EE",
    backgroundColor: "#EEF7FD",
  },
  filterButtonText: {
    color: "#023047",
    fontWeight: "700",
  },
  inactiveViewButton: {
    backgroundColor: "#FFF8E1",
    borderColor: "#F3C27A",
  },
  activeViewButton: {
    backgroundColor: "#EAF5FB",
    borderColor: "#D2E2EE",
  },
  chipsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 12,
    flexWrap: "wrap",
  },
  chipsLabel: {
    color: "#023047",
    fontSize: 13,
    fontWeight: "700",
  },
  chip: {
    backgroundColor: "#E8F5FD",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
  },
  chipGreen: {
    backgroundColor: "#E6F6EA",
  },
  chipText: {
    color: "#023047",
    fontSize: 12,
    fontWeight: "600",
  },
  chipGreenText: {
    color: "#2E7D32",
    fontSize: 12,
    fontWeight: "700",
  },
  toolbarFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: 8,
  },
  selectionMetaWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    flex: 1,
  },
  metaText: {
    color: "#4C6575",
    fontSize: 13,
    fontWeight: "600",
  },
  metaDivider: {
    color: "#A8BAC6",
    fontSize: 12,
  },
  selectAllButton: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D2E2EE",
    backgroundColor: "#FFFFFF",
  },
  selectAllButtonText: {
    color: "#023047",
    fontWeight: "700",
    fontSize: 13,
  },
  bulkActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
  },
  bulkActionsLabel: {
    color: "#607D8B",
    fontSize: 12,
    fontWeight: "700",
    marginRight: 2,
  },
  bulkActionsLabelCompact: {
    width: "100%",
    marginRight: 0,
  },
  massActionButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: "#2196F3",
    minWidth: 54,
  },
  massActionButtonCompact: {
    minWidth: 48,
    paddingVertical: 9,
    paddingHorizontal: 9,
    gap: 5,
  },
  massActionButtonMuted: {
    backgroundColor: "#F1F6FA",
    borderWidth: 1,
    borderColor: "#D2E2EE",
  },
  massActionButtonDisabled: {
    backgroundColor: "#D6E0E6",
  },
  massActionCount: {
    minWidth: 24,
    height: 24,
    paddingHorizontal: 6,
    borderRadius: 999,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
  },
  massActionCountMuted: {
    backgroundColor: "#E6EEF4",
  },
  massActionCountDisabled: {
    backgroundColor: "#E9EEF1",
  },
  massActionCountText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 12,
  },
  massActionCountTextMuted: {
    color: "#607D8B",
    fontWeight: "800",
    fontSize: 12,
  },
  massActionCountTextDisabled: {
    color: "#7D909D",
    fontWeight: "800",
    fontSize: 12,
  },
  historyInlineButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D2E2EE",
    backgroundColor: "#F7FBFF",
    marginLeft: "auto",
  },
  historyInlineButtonCompact: {
    marginLeft: 0,
    paddingVertical: 9,
    paddingHorizontal: 10,
  },
  historyInlineButtonText: {
    color: "#023047",
    fontWeight: "700",
    fontSize: 13,
  },
  historyInlineButtonTextCompact: {
    fontSize: 12,
  },

  headerRow: {
    flexDirection: "row",
    backgroundColor: "#F3F9FD",
    borderWidth: 1,
    borderColor: "#D6E4ED",
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 12,
    marginBottom: 10,
    alignItems: "center",
    gap: 8,
  },
  headerText: {
    fontWeight: "800",
    color: "#023047",
    fontSize: 13,
  },
  headerNameCell: {
    flex: 2.8,
  },
  headerDateCell: {
    flex: 1.4,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  headerStatsCell: {
    width: 170,
    alignItems: "center",
    paddingRight: 8,
  },
  headerActionsCell: {
    width: 200,
    textAlign: "center",
  },

  row: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E0EAF1",
    borderRadius: 20,
    paddingVertical: 10,
    paddingHorizontal: 10,
    marginBottom: 8,
    alignItems: "center",
    gap: 8,
  },
  rowEven: {
    backgroundColor: "#FBFDFF",
  },
  cardSelected: {
    borderColor: "#7DC595",
    backgroundColor: "#F2FBF5",
  },
  rowIdentityCell: {
    flex: 2.8,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  rowAvatar: {
    width: 30,
    height: 30,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F0F7FC",
    borderWidth: 1,
    borderColor: "#DDEAF2",
  },
  rowIdentityText: {
    flex: 1,
    minWidth: 0,
  },
  nameText: {
    fontWeight: "800",
    color: "#023047",
    fontSize: 14,
  },
  subtleRowText: {
    color: "#607D8B",
    fontSize: 11,
    marginTop: 2,
  },
  subtleLabel: {
    color: "#607D8B",
    fontSize: 11,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
    marginBottom: 3,
  },
  rowDateCell: {
    flex: 1.4,
    alignItems: "center",
  },
  rowDateText: {
    color: "#023047",
    fontWeight: "700",
    fontSize: 14,
  },
  rowStatsCell: {
    width: 170,
    alignItems: "center",
    paddingRight: 8,
  },
  rowStatsWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  rowStatPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 7,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: "#FFF6E7",
    borderWidth: 1,
    borderColor: "#FFE6B8",
  },
  rowStatPillText: {
    color: "#A65C00",
    fontWeight: "800",
    fontSize: 12,
  },
  rowActionsCell: {
    width: 200,
    alignItems: "flex-end",
    paddingLeft: 6,
  },
  rowActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
    flexWrap: "nowrap",
  },

  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#E0EAF1",
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 10,
  },
  cardHeaderLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  cardName: {
    fontWeight: "800",
    color: "#023047",
    fontSize: 15,
  },
  cardSub: {
    color: "#607D8B",
    marginTop: 2,
    fontSize: 12,
  },
  mobileStatusChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#F1F7FB",
    borderWidth: 1,
    borderColor: "#D2E2EE",
  },
  mobileStatusChipText: {
    color: "#023047",
    fontSize: 11,
    fontWeight: "800",
  },
  mobileStatsStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 10,
  },
  mobileStatPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: "#F7FBFF",
    borderWidth: 1,
    borderColor: "#E0EAF1",
  },
  mobileStatPillText: {
    color: "#023047",
    fontSize: 12,
    fontWeight: "800",
  },
  cardActionsRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    flexWrap: "wrap",
  },

  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: "#8AAAC1",
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: "#219EBC",
    borderColor: "#219EBC",
  },
  checkboxHitbox: {
    padding: 4,
  },

  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D6E4ED",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  tooltip: {
    position: "absolute",
    bottom: 46,
    left: "50%",
    transform: [{ translateX: -66 }],
    width: 132,
    backgroundColor: "#111",
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    zIndex: 999,
  },
  tooltipText: {
    color: "#FFFFFF",
    fontSize: 11,
    textAlign: "center",
  },
  statBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E0EAF1",
    backgroundColor: "#FFFFFF",
  },
  detailsButton: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#D6E4ED",
    backgroundColor: "#FFFFFF",
  },
  detailsButtonText: {
    color: "#023047",
    fontWeight: "800",
    fontSize: 11,
  },
  reactivateButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    paddingVertical: 9,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: "#2196F3",
  },
  reactivateButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 12,
  },

  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(7, 24, 39, 0.42)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modalBackdropTopAligned: {
    justifyContent: "flex-start",
    paddingTop: 152,
  },
  modalCard: {
    width: "100%",
    maxWidth: 420,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: "#D6E4ED",
    shadowColor: "#0A2A43",
    shadowOpacity: 0.12,
    shadowRadius: 22,
    shadowOffset: { width: 0, height: 12 },
    elevation: 6,
  },
  filterModalCard: {
    maxWidth: 440,
  },
  detailModalCard: {
    maxWidth: 540,
  },
  pushModalCard: {
    maxWidth: 460,
  },
  pushModalCardWide: {
    maxWidth: 620,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  modalTitleRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    flex: 1,
  },
  modalIconBadge: {
    width: 40,
    height: 40,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EAF5FB",
  },
  modalTitle: {
    fontWeight: "800",
    fontSize: 19,
    color: "#023047",
  },
  modalSubtitle: {
    marginTop: 2,
    color: "#607D8B",
    fontSize: 13,
    lineHeight: 18,
  },
  modalCloseIcon: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F7FBFF",
    borderWidth: 1,
    borderColor: "#D6E4ED",
  },
  optionLabel: {
    color: "#023047",
    fontWeight: "800",
    marginBottom: 6,
    fontSize: 13,
  },
  dropdownContainer: {
    position: "relative",
    marginBottom: 14,
    zIndex: 20,
  },
  dropdown: {
    borderWidth: 1,
    borderColor: "#D2E2EE",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 14,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#FAFCFE",
  },
  dropdownText: {
    color: "#023047",
    fontSize: 14,
    fontWeight: "600",
  },
  dropdownList: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#D2E2EE",
    borderRadius: 14,
    marginTop: 6,
    zIndex: 50,
    elevation: 8,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    paddingVertical: 4,
  },
  optionItem: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 10,
    marginHorizontal: 6,
    marginVertical: 2,
    backgroundColor: "#FFFFFF",
  },
  optionItemActive: {
    backgroundColor: "#EAF5FB",
  },
  optionText: {
    color: "#023047",
    fontWeight: "700",
    fontSize: 14,
  },
  optionTextActive: {
    color: "#023047",
  },
  modalFooterActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 6,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  modalPrimaryButton: {
    backgroundColor: "#2196F3",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
  },
  modalPrimaryText: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  modalGhostButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D2E2EE",
    backgroundColor: "#FFFFFF",
  },
  modalGhostButtonText: {
    color: "#023047",
    fontWeight: "800",
  },
  detailInfoCard: {
    backgroundColor: "#F8FBFE",
    borderRadius: 18,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E0EAF1",
    marginBottom: 14,
  },
  detailRowInline: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
    paddingVertical: 7,
  },
  detailKey: {
    color: "#607D8B",
    fontWeight: "700",
    fontSize: 13,
    flex: 1,
  },
  detailValue: {
    color: "#023047",
    fontWeight: "700",
    fontSize: 14,
    flex: 1.2,
    textAlign: "right",
  },
  detailSectionTitle: {
    fontWeight: "800",
    fontSize: 16,
    color: "#023047",
    marginBottom: 10,
  },
  detailStatsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 14,
  },
  detailStatCard: {
    flexBasis: "48%",
    flexGrow: 1,
    minWidth: 150,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E0EAF1",
  },
  detailStatLabel: {
    color: "#607D8B",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 6,
  },
  detailStatValue: {
    color: "#023047",
    fontSize: 18,
    fontWeight: "800",
  },
  dangerButton: {
    marginTop: 8,
    alignSelf: "flex-start",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 14,
    backgroundColor: "#C62828",
  },
  dangerButtonText: {
    color: "#FFFFFF",
    fontWeight: "800",
  },
  confirmBox: {
    marginTop: 10,
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#FFF8E1",
    borderWidth: 1,
    borderColor: "#FFE0B2",
  },
  confirmText: {
    color: "#6D4C41",
    marginBottom: 10,
    fontWeight: "700",
  },
  confirmActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 10,
  },
  confirmCancelText: {
    color: "#6D4C41",
    fontWeight: "700",
  },
  successText: {
    color: "#2E7D32",
    fontWeight: "800",
    marginBottom: 10,
  },
  errorText: {
    color: "#C62828",
    fontWeight: "700",
    marginBottom: 8,
  },
  targetSummaryCard: {
    padding: 14,
    borderRadius: 16,
    backgroundColor: "#F7FBFF",
    borderWidth: 1,
    borderColor: "#DDEAF2",
    marginBottom: 14,
  },
  targetSummaryLabel: {
    color: "#607D8B",
    fontSize: 12,
    fontWeight: "700",
    marginBottom: 4,
    textTransform: "uppercase",
  },
  targetSummaryValue: {
    color: "#023047",
    fontSize: 16,
    fontWeight: "800",
  },
  fieldLabel: {
    color: "#023047",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: "#D2E2EE",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    backgroundColor: "#FAFCFE",
    color: "#023047",
    fontSize: 16,
    marginBottom: 12,
  },
  textareaInput: {
    minHeight: 140,
    textAlignVertical: "top",
  },
  inlineStatusBox: {
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: "#F4F9FD",
    borderWidth: 1,
    borderColor: "#D6E4ED",
    justifyContent: "center",
    marginTop: -4,
    marginBottom: 10,
  },
  inlineStatusBoxHidden: {
    opacity: 0,
    backgroundColor: "transparent",
    borderColor: "transparent",
  },
  inlineStatus: {
    color: "#023047",
    fontWeight: "600",
    lineHeight: 20,
  },

  errorBanner: {
    color: "#B42318",
    backgroundColor: "#FEF3F2",
    borderWidth: 1,
    borderColor: "#FECACA",
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
    fontWeight: "700",
  },
  emptyStateCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    paddingVertical: 34,
    paddingHorizontal: 24,
    borderWidth: 1,
    borderColor: "#D8E4EE",
    alignItems: "center",
    justifyContent: "center",
  },
  emptyStateIcon: {
    width: 64,
    height: 64,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EAF5FB",
    marginBottom: 14,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: "800",
    color: "#023047",
    textAlign: "center",
    marginBottom: 8,
  },
  emptyStateDescription: {
    color: "#607D8B",
    textAlign: "center",
    lineHeight: 21,
    maxWidth: 520,
  },
  listContent: {
    paddingBottom: 24,
  },
  loadMoreButton: {
    alignSelf: "center",
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 14,
    backgroundColor: "#EAF5FB",
    borderWidth: 1,
    borderColor: "#D2E2EE",
    marginTop: 8,
  },
  loadMoreText: {
    color: "#023047",
    fontWeight: "800",
  },
  endOfListText: {
    textAlign: "center",
    color: "#607D8B",
    marginTop: 10,
    fontWeight: "600",
  },
});
