import { StyleSheet } from "react-native";

export const clientesStyles = StyleSheet.create({
  searchRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 10,
  },
  searchInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    padding: 10,
    backgroundColor: "#fff",
  },
  filterButton: {
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cfd8dc",
    backgroundColor: "#e3f2fd",
    justifyContent: "center",
  },
  filterButtonText: {
    color: "#023047",
    fontWeight: "600",
  },
  chipsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 8,
    flexWrap: "wrap",
  },
  chipsLabel: { color: "#023047", fontSize: 13, fontWeight: "600" },
  chip: {
    backgroundColor: "#e3f2fd",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
  },
  chipGreen: {
    backgroundColor: "#e8f5e9",
  },
  chipText: { color: "#023047", fontSize: 12 },
  chipGreenText: { color: "#2e7d32", fontSize: 12 },

  sendButton: {
    alignSelf: "flex-start",
    flexGrow: 0,
    flexShrink: 0,
    maxWidth: 230,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#2196F3",
    marginBottom: 10,
  },
  sendButtonDisabled: {
    backgroundColor: "#cfd8dc",
  },
  sendButtonText: { color: "#fff", fontWeight: "600" },
  sendButtonTextDisabled: { color: "#777" },

  metaRow: {
    marginBottom: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  metaText: {
    color: "#607d8b",
    fontSize: 12,
    flex: 1,
  },
  selectAllButton: {
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cfd8dc",
    backgroundColor: "#fff",
  },
  selectAllButtonText: {
    color: "#023047",
    fontWeight: "700",
    fontSize: 12,
  },

  headerRow: {
    flexDirection: "row",
    backgroundColor: "#e3f2fd",
    borderWidth: 1,
    borderColor: "#cfd8dc",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginBottom: 8,
    alignItems: "center",
    gap: 8,
  },
  headerText: { fontWeight: "bold", color: "#023047" },

  row: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 8,
    marginBottom: 8,
    alignItems: "center",
    gap: 8,
  },
  rowEven: {
    backgroundColor: "#fafafa",
  },
  nameCell: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    minWidth: 0,
  },
  nameText: {
    fontWeight: "600",
    color: "#023047",
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  cardSelected: {
    borderColor: "#5cb85c",
    backgroundColor: "#e6f7ec",
  },
  cardHeader: { flexDirection: "row", alignItems: "center", marginBottom: 6, gap: 8 },
  cardSub: { color: "#555", marginTop: 2 },
  cardFooter: {
    marginTop: 6,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  cardFooterText: { color: "#666", flex: 1 },

  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: "#023047",
    backgroundColor: "transparent",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: "#e6f7ec",
    borderColor: "#5cb85c",
  },
  checkboxHitbox: { padding: 4 },

  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.4)",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  modalCard: {
    backgroundColor: "#fff",
    borderRadius: 10,
    padding: 16,
    width: "100%",
    maxWidth: 320,
    gap: 10,
  },
  modalTitle: { fontWeight: "700", fontSize: 16, color: "#023047" },
  optionItem: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    backgroundColor: "#f9f9f9",
  },
  optionItemActive: {
    borderColor: "#2196F3",
    backgroundColor: "#E3F2FD",
  },
  optionText: { color: "#023047", fontWeight: "600" },
  optionTextActive: { color: "#023047" },
  modalClose: { marginTop: 4, alignSelf: "flex-end", paddingVertical: 8, paddingHorizontal: 12 },

  modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10 },
  modalPrimaryButton: {
    backgroundColor: "#2196F3",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  modalPrimaryText: { color: "#fff", fontWeight: "700" },

  loadMoreButton: {
    alignSelf: "center",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: "#8ecae6",
    marginTop: 6,
  },
  loadMoreText: { color: "#023047", fontWeight: "bold" },

  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    padding: 10,
    backgroundColor: "#fff",
  },

  rowActions: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 8,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cfd8dc",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  tooltip: {
    position: "absolute",
    bottom: 40,
    left: "50%",
    transform: [{ translateX: -60 }],
    width: 120,
    backgroundColor: "#111",
    paddingVertical: 6,
    paddingHorizontal: 8,
    borderRadius: 8,
    zIndex: 999,
  },
  tooltipText: {
    color: "#fff",
    fontSize: 11,
    textAlign: "center",
  },
  statBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    backgroundColor: "#fff",
  },
  statValue: { color: "#023047", fontWeight: "700", fontSize: 12 },

  detailsButton: {
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#cfd8dc",
    backgroundColor: "#fff",
  },
  detailsButtonText: {
    color: "#023047",
    fontWeight: "700",
    fontSize: 12,
  },

  detailTitle: {
    fontWeight: "800",
    fontSize: 16,
    color: "#023047",
    marginBottom: 8,
  },
  detailRow: {
    color: "#023047",
    marginBottom: 6,
  },
  detailDivider: {
    height: 1,
    backgroundColor: "#eee",
    marginVertical: 10,
  },
  dangerButton: {
    marginTop: 8,
    backgroundColor: "#c62828",
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  dangerButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  confirmBox: {
    marginTop: 10,
    padding: 10,
    borderRadius: 8,
    backgroundColor: "#fff8e1",
    borderWidth: 1,
    borderColor: "#ffe0b2",
  },
  confirmText: {
    color: "#6d4c41",
    marginBottom: 8,
    fontWeight: "600",
  },
  confirmActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: 10,
  },
  successText: {
    color: "#2e7d32",
    fontWeight: "700",
    marginBottom: 6,
  },
  errorText: {
    color: "#c62828",
    fontWeight: "600",
    marginBottom: 6,
  },
});
